### PR TITLE
log to a separate file in a directory owned by the etcd user

### PR DESCRIPTION
**Pull request by willejs**
I want to be able to get logs into logstash, which means they need to readable by other users and not owned by root (which the upstart logs are)

### CODE REVIEW

**Comment by willejs** [comment]
@spheromak sorry, will address this soon

**Comment by spheromak** [comment]
thanks @willejs I will work on fixing build this week. Need to give this cook some love anyhow and support etcd 2.0

**Comment by willejs** [comment]
I also need etcd 2.0 support, I haven't looked at the changelog yet though.
I am most likely going to look at that tomorrow am.

**Comment by willejs** [comment]
@spheromak Can you merge this in now, then i will work on 2.0 in a separate branch and submit a pr.

**Pull request closed without merging**
